apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  config.json: |
    {
      "environment" : "trial"
    }
# kubectl create configmap test-config --from-file ./golang/configs/config.json
