apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MoSalah5/argo-deployment.git
    targetRevision: HEAD
    path: argo/test-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false